-- GOI DATA BASE 
USE [master]
GO
--TAO CO SO DU LIEU CO TEN LAB02
CREATE DATABASE Lab02 ON
(NAME = Lab02,
    FILENAME = 'F:\Database\Lab02.mdf',
    SIZE = 10,
    MAXSIZE = 50,
    FILEGROWTH = 5)
LOG ON
(NAME = Lab02_log,
    FILENAME = 'F:\Database\lab02log.ldf',
    SIZE = 5 MB,
    MAXSIZE = 25 MB,
    FILEGROWTH = 5 MB);
GO
--Goi co so du lieu Lab02
USE [Lab02]
GO
--Khai bao 1 bien Name,va gan gia tri va in ra 
DECLARE @Name Nvarchar (30)
--GAN GIA  TRI 
SET @Name = 'MinhHa'
--IN RA TEN BIEN
SELECT @Name
---KHAI BAO 1 BIEN AGE GAN GIA TRI VA IN RA
DECLARE @AGE INT 
SET @AGE =22
SELECT @AGE

GO
---TAO 1 BANG EMPLOYEE 
 CREATE TABLE EMPLOYEE 
 ( ID INT PRIMARY KEY ,
 FullName NVARCHAR(35),
 Gender BIT ,
 BirthDay DATETIME,
 Address NVARCHAR (MAX),
 Email VARCHAR (50),
 Salary FLOAT )
  
  GO
  --THEM COT PHONE CHO BANG EMPLOYEE
  ALTER TABLE EMPLOYEE
  ADD Phone VARCHAR (20)
  GO
   --- THEM VAO 5 BAN GGHI DU LIEU
DELETE FROM EMPLOYEE WHERE ID IN (1, 2, 3, 4, 5);
   --- THEM VAO 5 BAN GGHI DU LIEU
   INSERT INTO EMPLOYEE (ID,FullName,Gender,BirthDay,Address,Email,Salary,Phone) VALUES
   (1,'VU MINH HA',1,'2003-10-06','ND','minhha1192003@gmail.com',100000000,'0353199540'),
   (2,'VU MINH HOANG',1,'2003-08-06','NB','minhha1192003@gmail.com',2000000000,'0353199540'),
   (3,'VU MINH HAI',0,'2003-11-06','HN','minhha1192003@gmail.com',400000000,'0353199540'),
   (4,'VU MINH HAN',0,'2003-10-06','HN','minhha1192003@gmail.com',150000000,'0353199540'),
   (5,'VU MINH HATT',1,'2003-04-07','ND','minhha1192003@gmail.com',130000000,'0353199540')
   GO
   --IN RA TAT CA NHAN VIEN
   SELECT * FROM EMPLOYEE
   --DUA RA CAC NHAN VIEN CO TREN 20000000
   GO
      SELECT * FROM EMPLOYEE WHERE Salary >200000000
-- DUA NHAN VIEN CO QUE HA NOI
GO
SELECT FullName,Address FROM EMPLOYEE WHERE Address ='HN'
-- DUA RA NHAN VIEN CO SINH NHAT VAO THANG NAY 
GO 
SELECT * FROM EMPLOYEE WHERE MONTH(BirthDay)= MONTH(GETDATE())
---- DUA RA TEN VA TUOI HIEN TAI KEM THEM COT BIRTHDAY
SELECT 
    FullName,
    BirthDay,
    DATEDIFF(YEAR, BirthDay, GETDATE()) 
        - CASE 
            WHEN MONTH(BirthDay) > MONTH(GETDATE()) 
              OR (MONTH(BirthDay) = MONTH(GETDATE()) AND DAY(BirthDay) > DAY(GETDATE()))
            THEN 1 
            ELSE 0 
          END AS Age
FROM EMPLOYEE;
---SUA TEN NHAN VIEN CO ID BANG 1
GO 
UPDATE EMPLOYEE SET FullName =' JONH' WHERE ID=1
 GO
 SELECT * FROM EMPLOYEE
 ---- XOA NHAN VIEN CO TUOI TREN 50
 GO 
 UPDATE EMPLOYEE SET BirthDay='1960-06-03' WHERE ID=2
  GO 
  SELECT * FROM EMPLOYEE
 GO 
 INSERT INTO EMPLOYEE ([ID], [FullName], [Gender], [BirthDay], [Address], [Email], [Salary], [Phone]) VALUES
 (6,'VU MINH HA',1,'1950-10-06','ND','minhha1192003@gmail.com',100000000,'0353199540')
 GO 
 SELECT * FROM EMPLOYEE
 GO
 DELETE FROM EMPLOYEE
WHERE DATEDIFF(YEAR, BirthDay, GETDATE()) 
    - CASE 
        WHEN MONTH(BirthDay) > MONTH(GETDATE()) 
          OR (MONTH(BirthDay) = MONTH(GETDATE()) AND DAY(BirthDay) > DAY(GETDATE()))
        THEN 1 
        ELSE 0 
      END > 50;
GO 
SELECT * FROM EMPLOYEE
--- DEM SO NHAN VIEN 
SELECT COUNT(*) AS TOTALEMPLOYEE
FROM EMPLOYEE
