------TAO VIEW 
----CAU 1
SELECT * FROM SinhVien
SELECT HOSV+' '+TENSV AS HOTEN ,MAKH,NOISINH,HOCBONG FROM SinhVien WHERE HOCBONG >10000 AND NOISINH =N'Tp. HCM'
GO
CREATE VIEW vw_HocBong
AS
SELECT HOSV + ' ' + TENSV AS HOTEN, MAKH, NOISINH, HOCBONG
FROM SinhVien
WHERE HOCBONG > 100000 AND NOISINH = N'Tp. HCM'
GO
SELECT * FROM vw_HocBong
GO 
DROP VIEW vw_HocBong
-----DS SINH VIEN KHOA ANH VAN VA KHOA TRIET 
SELECT * FROM SINHVIEN WHERE MAKH IN ('AV','TR')
GO
CREATE VIEW vw_Khoa
as 
SELECT MASV,MAKH,PHAI FROM SinhVien WHERE MAKH IN ('AV','TR')
GO
SELECT * FROM vw_Khoa
GO 
-----CHO BT NHUNG SINH VIEN 
