----in ra du lieu cac bang 
select * from [dbo].[Ketqua]
SELECT *  FROM [dbo].[Khoa]
SELECT * FROM [dbo].[MonHoc]
SELECT * FROM [dbo].[SinhVien]
---- cau 1
select * FROM MONHOC
--- LIET KE DANH SACH SINH VIEN CAU2  MA SINH VIEN TANG DAN 
GO 
SELECT MASV,HOSV,TENSV,HOCBONG FROM SinhVien
ORDER BY MASV ASC
-----CAU 3 ---DANH SACH DUOC SAP XEP THEO THU TU CUA TEN
GO
SELECT MASV,TENSV,PHAI,DAY(NGAYSINH) DAY FROM SinhVien
ORDER BY TENSV ASC 
------CAU4 NGAY SINH TANG DAN VA HOC BONG GIAM DAN
GO
SELECT HOSV+' '+TENSV HOTEN ,DAY(NGAYSINH) DAY,HOCBONG FROM SinhVien
ORDER BY DAY(NGAYSINH) ASC,
HOCBONG DESC 
----CAU5 DS MON HOC BAT DAU BANG CHU T CAU5 []%
GO
SELECT * FROM MONHOC 
WHERE TENMH LIKE N'[T]%'
-----LAY TAT CA SINH VIEN CO CHU CAI CUOI CUNG TRONG TEN LA I
GO 
SELECT HOSV+' '+TENSV HOTEN,PHAI,DAY(NGAYSINH) DAY 
FROM SINHVIEN
WHERE TenSV LIKE N'%[I]'
-----LAY DANH SACH KHOA CO KY TU THU2 LA 'N',% LA CAC KY TU DANG SAU
GO
SELECT MAKH,TENKH FROM Khoa
WHERE TenKH LIKE N'_N%'
GO
----LIET KE NHUNG SINH VIEN CO MA HO CO CHUA CHU THI CAU 8
SELECT * FROM SinhVien
WHERE LOWER(HOSV) LIKE N'%THỊ%'
GO
------CAU 9 KYTU DAU TIEN CUA TEN NAM TRONG KHOANG TU A DEN M TANG DAN THEO TEN SV 
SELECT MASV,HOSV+' '+TENSV HOTEN ,PHAI,HOCBONG
FROM SinhVien
---WHERE TENSV >= 'A 'AND TENSV <='M'
WHERE TENSV BETWEEN 'A' AND 'M'
ORDER BY TENSV ASC
----DS SACH SINH VIEN KHOA ANH VAN
GO
SELECT MASV,HOSV+' '+TENSV HOTEN,DAY(NGAYSINH) DAY,MAKH
FROM SinhVien
WHERE MAKH=N'AV'
----WHERE MAKH LIKE N'AV%'
GO
----DS SINH VIEN KHOA VAT LY SAP XEP THEO THU TU NGAY SINH GIAM DAN CAU12
SELECT MASV,HOSV+' '+TENSV HOTEN,DAY(NGAYSINH) DAY,MAKH
FROM SinhVien
WHERE MAKH LIKE N'VL%'
ORDER BY DAY(NGAYSINH) DESC
---DS SINH VIEN CO HK BONG LONNHON 500000 VA SAP XEP THEO THU TU MA KHOA GIAM DAN CAU 13 
GO
SELECT MASV,HOSV+' '+TENSV HOTEN,DAY(NGAYSINH) DAY,MAKH,HOCBONG
FROM SinhVien
WHERE HocBong >500000
ORDER BY MAKH DESC 
GO
---- LIET KE SINH VIEN CO NGAY SINH 20/12/1987 CAU 14 
SELECT MASV,HOSV+' '+TENSV HOTEN,HOCBONG,NgaySinh
FROM SinhVien
---WHERE NgaySinh >CONVERT(DATETIME,('19871220'))
WHERE NGAYSINH ='1987-12-20'

GO 
---CAC SINH VIEN SINH SAU NGAY 20-12-1987,SAP XEP THEO THU TU NGAY SINH GIAM DAN
SELECT MASV,HOSV+' '+TENSV HOTEN,HOCBONG,NgaySinh,NOISINH,DAY(NGAYSINH) DAY
FROM SinhVien
---WHERE NgaySinh >'1987-12-20'
WHERE NgaySinh >(CONVERT (DATETIME,'19871220'))
ORDER BY DAY(NGAYSINH) DESC
GO
-----LIET KE SINH VIEN CO HOC BONG LON HON 10000 VA SINH SONG O THANH PHO HCM
SELECT MASV,HOSV+' '+TENSV HOTEN,HOCBONG,NgaySinh,NoiSinh
FROM SinhVien
WHERE HocBong >10000 AND  NOISINH LIKE N'%Tp. HCM%'
GO
-----DS SINH VIEN KHOA ANH VAN VA KHOA TRIET 
SELECT MASV,MAKH,PHAI 
FROM SinhVien
WHERE MAKH IN ('AV','TR')
---WHERE MAKH = 'AV' OR MAKH='TR'

------DS SINH VIEN CO NGAY SINH TU 1-1-1968  DEN NGAY 5-6-1992 
SELECT MASV,NGAYSINH,HOCBONG,NOISINH 
FROM SINHVIEN
WHERE NGAYSINH BETWEEN CONVERT(DATE,'19680101') AND CONVERT (DATE,'19920605')
 GO 
 -----DS SINHHVIEN CO HOC BONG TU 200000 DEN 80000
 SELECT MASV,NGAYSINH,PHAI,MAKH,HOCBONG
 FROM SINHVIEN
 WHERE HOCBONG BETWEEN 20000 AND 800000 
   GO 
-----  BIEU DIEN GIOI TINH DUOI DANG SO NHI PHAN 
SELECT * ,CASE WHEN PHAI =1 THEN N'NAM'-- WHEN PHAI = 0 THEN N'NU' 
ELSE N'NU' END AS GIOITINH
 FROM SINHVIEN
 GO 
 -----TINH TUOI HIEN TAI CAU 26
 SELECT MASV,NOISINH,MAKH, DATEDIFF(YEAR, NGAYSINH, GETDATE()) AS TUOI
 FROM SINHVIEN
GO 
----TUOI >20
SELECT MASV,NOISINH,MAKH, DATEDIFF(YEAR, NGAYSINH, GETDATE()) AS TUOI
 FROM SINHVIEN
 WHERE NgaySinh >20
GO 
----- SU DUNG HAM TRU VAN 
SELECT *,CASE WHEN PHAI =1 THEN N'NAM'-- WHEN PHAI = 0 THEN N'NU' 
ELSE N'NU' END AS GIOITINH, DATEDIFF(YEAR, NGAYSINH, GETDATE()) AS TUOI
 FROM SINHVIEN
 ORDER BY NGAYSINH ASC
GO 
----DS SINH VIEN SINH VAO THANG 2-1994
SELECT * ,DAY(NGAYSINH) DAY
FROM SINHVIEN
WHERE YEAR(NGAYSINH) = 1994 AND MONTH(NGAYSINH) = 2;
-- CACH KHAC KO SU DUNG HAM THI DUNG SO SANH BETWEEN

------HK BONG >500000 CAO NGUOC LAI SE LA TRUNG BINH
SELECT *, CASE WHEN HOCBONG>=500000 THEN N'CAO'
ELSE  N'TRUNGBINH' END AS DANHGIA
FROM SINHVIEN
go 
------TINH TOAN THONG KE DU LIEU 
SELECT * FROM Ketqua
SELECT * FROM MONHOC 
------ DIEM TRUNG BINH THEO TUNG MON HOC 
SELECT MH.MAMH, MH.TENMH, AVG(KQ.DIEM) AS TRUNGBINHDIEM
FROM KETQUA KQ
JOIN MONHOC MH ON KQ.MAMH = MH.MAMH
GROUP BY MH.MAMH, MH.TENMH;
------SOMONTHI CUA TUNG SINH VIEN
GO
SELECT * FROM SINHVIEN
SELECT * FROM MONHOC
SELECT * FROM Khoa

SELECT SV.MASV, SV.HOSV + ' ' + SV.TENSV AS HOTEN, COUNT(KQ.MAMH) AS SOMONTHI
FROM SINHVIEN SV
JOIN KETQUA KQ ON SV.MASV = KQ.MASV
GROUP BY SV.MASV, SV.HOSV, SV.TENSV;

----SELECT <BOTU,TOP,PERCENT,...> <SELECT LIST---CAC COT>
----FROM <BANG 1>
----INMER JOIN,LEFT JOIN,RIGHT JOIN<TENBANG_2> ON <TEN.BANG _1>.<TENCOT> =<TENCOTBANG_2>.<TENCOT>...//AND <TENBIEUTHUCDK>
----WHERE <MENHDEDK_1> AND/OR <MENH DEDK_2>...
----GROUP BY
----HAVING 
----ORDER BY DESC,ASC

----SUBQUERY
----TRUY VAN SU DUNGTHAM SO


-----BAI 2.8
-----BAI6.5
SELECT * FROM SINHVIEN SV
INNER JOIN KHOA KH ON SV.MaKH=KH.MaKH
WHERE TenKH =N'TIN HỌC'




----bai5.11
--SINHVIEN :MASV,HOTENSV 
--KETQUA :DIEM
--MON: TENMON
-----> DS SINH VIEN CO DIEM CAO NHAT VOI MOI MON
SELECT MASV,HOSV+' '+TENSV AS HOTEN FROM SINHVIEN
SELECT * FROM MONHOC
SELECT * FROM KETQUA

SELECT  KQ.MaSV,HoSV + ' ' + TenSV AS N'Họ và tên',MH.TenMH, KQ.Diem FROM  Ketqua KQ
INNER JOIN 
(SELECT MaMH, MAX(Diem) AS Diem FROM  Ketqua GROUP BY MaMH) KQM ON KQ.MaMH = KQM.MaMH AND KQ.Diem = KQM.Diem
INNER JOIN [dbo].[SinhVien] SV ON KQ.MaSV = SV.MaSV
INNER JOIN MonHoc MH ON MH.MaMH = KQ.MaMH
-------tinh toan thong ke so lieu 
----bai3.3
----sinhvien: tensinhvien,phai
----khoa: ten khoa 
----ketqua: tong diem thi
SELECT * FROM SINHVIEN
SELECT * FROM KHOA
SELECT * FROM KETQUA

SELECT 
    KQ.MaSV,
    SV.TENSV,
    SV.PHAI,
    KH.TENKH,
    SUM(KQ.DIEM) AS TONGDIEM
FROM 
    KETQUA KQ
INNER JOIN 
    SINHVIEN SV ON KQ.MaSV = SV.MaSV
INNER JOIN 
    KHOA KH ON SV.MaKH = KH.MaKH
GROUP BY  
    KQ.MaSV, SV.TENSV, SV.PHAI, KH.TENKH;
GO 
----CACH2 DUNG SUBQUERY
SELECT SV.MASV,SV.TENSV,SV.PHAI,KH.TENKH,KQ.TONGDIEM FROM SINHVIEN SV
INNER JOIN KHOA KH ON SV.MaKH =KH.MAKH
INNER JOIN (SELECT MASV,SUM(DIEM) TONGDIEM FROM Ketqua GROUP BY MASV) KQ  ON KQ.MASV =SV.MaSV
go
-----BAI 3.4
---KHOA : TEN KHOA 
-----> TONG SO SINHVIEN MOI KHOA
SELECT * FROM SINHVIEN
SELECT * FROM KHOA 

SELECT KH.TENKH,COUNT(SV.MASV) TONGSOHS FROM SinhVien SV
INNER JOIN KHOA KH ON SV.MAKH = KH.MAKH
GROUP BY KH.TenKH
GO
----SUDUNG SUBQUERY
SELECT KH.TENKH,SV.TONGSOSV FROM KHOA KH 
INNER JOIN (SELECT COUNT(MASV) TONGSOSV,MAKH FROM SINHVIEN  GROUP BY MAKH) SV ON KH.MaKH =SV.MaKH
GO
----CAU 3.5 
----SINHVIEN: HOTENSINHVIEN
----KETQUA : DIEM
------> DIEM CAO NHAT CUA MOI SINH VIEN 
SELECT * FROM KETQUA
SELECT * FROM SINHVIEN

SELECT KQ.MASV,SV.TENSV,MAX(KQ.DIEM) DIEMCAONHAT FROM KETQUA KQ 
INNER JOIN SINHVIEN SV ON KQ.MaSV =SV.MaSV
GROUP BY SV.TENSV,KQ.MASV
---DUNG SUBQUERY 
SELECT SV.MASV,SV.TENSV,KQ.DIEMCAONHAT FROM SINHVIEN SV
INNER JOIN (SELECT MASV,MAX(DIEM) DIEMCAONHAT FROM Ketqua  GROUP BY MASV) KQ ON SV.MASV =KQ.MASV
GO 
-----BAI 3.6 THONG TIN MON HOC CO SO TIET NHIEU NHAT  TEN MONHOC SO TIET 
SELECT TENMH, SOTIET
FROM MONHOC
WHERE SOTIET = (
    SELECT MAX(SOTIET)
    FROM MONHOC
);
GO 
----3.7 CHO BT HOC BONG CAO NHAT CUA TUNG KHOA 
SELECT * FROM KHOA 
SELECT * FROM SINHVIEN
SELECT KH.MAKH,KH.TENKH,MAX(SV.HOCBONG) MAXHB FROM KHOA KH
INNER JOIN SINHVIEN SV ON KH.MaKH =SV.MaKH
GROUP BY KH.MAKH,KH.TENKH
-----truy van con 
GO 
----5.1 DS SINH VIEN CHUA THI MON NAO
SELECT * FROM SINHVIEN
SELECT * FROM Khoa
SELECT * FROM MonHoC
SELECT * FROM KETQUA
SELECT 
  SV.MASV, 
  SV.TENSV, 
  SV.PHAI, 
  KH.TENKH
FROM 
  SINHVIEN SV
JOIN 
  KHOA KH ON SV.MAKH = KH.MAKH
WHERE 
  SV.MASV NOT IN (
    SELECT DISTINCT MASV 
    FROM KETQUA
  );
  go 
------bai5.12 SINH VIEN CO HOC BONG CAO NHAT MOI KHOA 
SELECT* FROM SINHVIEN
SELECT * FROM KHOA 
GO 
SELECT SV.MASV,KH.TENKH,ISNULL(SV.HOCBONG,0) HOCBONG FROM KHOA KH
INNER JOIN (SELECT MASV,MAKH,MAX(HOCBONG) AS HOCBONG FROM SINHVIEN GROUP BY MAKH,MASV) SV ON KH.MaKH = SV.MAKH
go 
SELECT SV.MASV,KH.TENKH,SV.HOCBONG FROM SINHVIEN SV
INNER JOIN
KHOA KH ON SV.MaKH =KH.MaKH
INNER JOIN 
(SELECT MAKH,MAX(HOCBONG) AS MAX_HOCBONG FROM SINHVIEN GROUP BY MAKH) HB ON SV.MAKH =HB.MaKH AND SV.HocBong=HB.MAX_HOCBONG
GO 
SELECT SV.MASV, SV.HOCBONG, SV.NOISINH, KH.TENKH
FROM SINHVIEN SV
INNER JOIN KHOA KH ON SV.MaKH = KH.MaKH
WHERE EXISTS (
    SELECT 1
    FROM SINHVIEN SV_TIN
    INNER JOIN KHOA KH_TIN ON SV_TIN.MaKH = KH_TIN.MaKH
    WHERE KH_TIN.TENKH =N'TIN HỌC'
      AND SV.HOCBONG = SV_TIN.HOCBONG
      AND SV.NOISINH = SV_TIN.NOISINH
)
go
------5.5 cho bt nhung sinh vien khoa anh van chua thi mon co so du lieu
SELECT * FROM SINHVIEN
SELECT * FROM KHOA 
SELECT * FROM MONHOC
SELECT * FROM KETQUA

-- Danh sách những sinh viên khoa Anh Văn chưa thi môn Cơ sở dữ liệu
SELECT SV.MASV, SV.TENSV
FROM SINHVIEN SV
INNER JOIN KHOA KH ON SV.MAKH = KH.MAKH
WHERE KH.TENKH = 'Anh Văn' 
AND SV.MASV NOT IN (
    SELECT MASV 
    FROM KETQUA KQ
    INNER JOIN MONHOC MH ON KQ.MAMH = MH.MAMH
    WHERE MH.TENMH = 'Cơ sở dữ liệu'
);
----------cau 5.6 danhsach sinh vien KHOA LY CHUA THI MON NAO
SELECT SV.MASV, SV.TENSV
FROM SinhVien SV
JOIN Khoa KH ON SV.MAKH = KH.MAKH
WHERE KH.TENKH = 'Tin học'
  AND SV.MASV NOT IN (
    SELECT DISTINCT MASV
    FROM KetQua
  );
  ------
  SELECT SV.MASV, SV.TENSV
FROM SinhVien SV
JOIN Khoa KH ON SV.MAKH = KH.MAKH
LEFT JOIN KetQua KQ ON SV.MASV = KQ.MASV
WHERE KH.TENKH = 'Tin học'
  AND KQ.MASV IS NULL;
  ---------5.11------ds sinh vien co diem cao nhat ung voi moi mon 
 SELECT KQ.MASV,SV.TENSV,MH.TENMH,KQ.DIEM FROM Ketqua KQ 
 INNER JOIN SinhVien SV ON KQ.MaSV =SV.MASV
 INNER JOIN MonHoc MH ON KQ.MaMH = MH.MaMH
 INNER JOIN (SELECT MAMH,MAX(DIEM) MAXDIEM FROM Ketqua GROUP BY MAMH) MAXDIEMTUNGMON ON KQ.MaMH =MAXDIEMTUNGMON.MAMH AND KQ.Diem =MAXDIEMTUNGMON.MAXDIEM
 ----------5.12-------cac sinh vien co hoc bong cao nhat theo tung khoa 
 SELECT SV.MASV,KH.TENKH,SV.HOCBONG FROM SinhVien SV
 INNER JOIN KHOA KH ON SV.MaKH =KH.MaKH
 INNER JOIN (SELECT MAKH,MAX(HOCBONG) MAXHB,NoiSinh FROM SINHVIEN GROUP BY MaKH) MAXHBB ON SV.MaKH = MAXHBB.MAKH AND SV.HocBong = MAXHBB.MAXHB
 ---------cau 5.10 in ra ds sinh vien khoa ly co cung noi sinh sinh voi sinh vien co hoc bong cao nhat
SELECT SV.MASV, SV.TENSV, SV.NOISINH, KH.TENKH
FROM SinhVien SV
JOIN Khoa KH ON SV.MAKH = KH.MAKH
WHERE KH.TenKH = N'Tin học'
  AND SV.NOISINH IN (
      SELECT SV2.NOISINH
      FROM SinhVien SV2
      JOIN Khoa KH2 ON SV2.MAKH = KH2.MAKH
      WHERE KH2.TenKH = N'Tin học'
        AND SV2.HocBong = (
            SELECT MAX(HocBong)
            FROM SinhVien SV3
            JOIN Khoa KH3 ON SV3.MAKH = KH3.MAKH
            WHERE KH3.TenKH = N'Tin học'
        )
  );

