------TAO VIEW 
----CAU 1
SELECT * FROM SinhVien
SELECT HOSV+' '+TENSV AS HOTEN ,MAKH,NOISINH,HOCBONG FROM SinhVien WHERE HOCBONG >10000 AND NOISINH =N'Tp. HCM'
GO
CREATE VIEW vw_HocBong
AS
SELECT HOSV + ' ' + TENSV AS HOTEN, MAKH, NOISINH, HOCBONG
FROM SinhVien
WHERE HOCBONG > 100000 AND NOISINH = N'Tp. HCM'
GO
SELECT * FROM vw_HocBong
GO 
DROP VIEW vw_HocBong
-----DS SINH VIEN KHOA ANH VAN VA KHOA TRIET 
SELECT * FROM SINHVIEN WHERE MAKH IN ('AV','TR')
GO
CREATE VIEW vw_Khoa
as 
SELECT MASV,MAKH,PHAI FROM SinhVien WHERE MAKH IN ('AV','TR')
GO
SELECT * FROM vw_Khoa
GO 
-----CHO BT NHUNG SINH VIEN sinh ngay 1/1/1986 den 5/6/1992
SELECT * FROM SINHVIEN
WHERE NgaySinh BETWEEN '1986-01-01' AND '1992-06-05'
GO
CREATE VIEW vw_NGAYSINH
as 
SELECT MASV,NgaySinh,NoiSinh,HocBong FROM SINHVIEN
WHERE NgaySinh BETWEEN '1986-01-01' AND '1992-06-05'
GO
-----HOCBONG
CREATE VIEW vw_HOCBONG
as 
SELECT MASV,NgaySinh,PHAI,MAKH FROM SINHVIEN
WHERE HOCBONG BETWEEN 20000 AND 80000
GO
------SOTIET 
SELECT * FROM MonHoc
GO
CREATE VIEW vw_monhoc
as 
select MAMH,TENMH,SOTIET FROM MonHoc WHERE SOTIET BETWEEN 40 AND 60
GO
SELECT * FROM vw_monhoc
--------cau 6- liet ke so hs cua khoa anh van
go
CREATE VIEW vw_cau6
as
select MaSV,hosv+''+TenSV AS HOTEN,CASE PHAI WHEN 1 THEN N'NAM' ELSE N'NU' END AS GIOITINH
from sinhvien
WHERE PHAI = 1  AND MAKH =N'AV'
go
SELECT  * FROM vw_cau6
go
--------cau 7----
CREATE VIEW vw_cau7
as
SELECT HOSV,TENSV,NgaySinh,NoiSinh
FROM SINHVIEN
WHERE NOISINH =N'Hà Nội' AND NGAYSINH > CONVERT(DATETIME,'19900101')
go
select * from vw_cau7
go
------cau 8
CREATE VIEW vw_cau8
as 
select * from sinhvien
where phai = 0 and tensv like N'%n%'
go
select * from vw_cau8
go
-----cau9 
CREATE VIEW vw_cau9
as
select * from sinhvien
where phai=1 and makh =N'TH' and ngaysinh > CONVERT(DATETIME,'19860530')
go
------cau10 
CREATE VIEW vw_cau10
as 
SELECT HOSV+' ' +TENSV AS HOTEN,CASE PHAI WHEN 1 THEN N'NAM' ELSE N'NU' END AS GIOITINH,
CONVERT(nvarchar,NgaySinh,111) AS NGAYSINH
FROM SINHVIEN
go 
SELECT * FROM vw_cau10
GO 
-----cau11----
CREATE VIEW vw_cau11
as
select MaSV,MaKH,NoiSinh,DATEDIFF(YEAR,NgaySinh,GETDATE())AS TUOI
from sinhvien
go
-------cau 12 ---
SELECT * FROM KHOA
GO 
CREATE VIEW vw_cau12
as
select hosv +' ' +tensv as HOTEN,DATEDIFF(YEAR,NGAYSINH,GETDATE()) AS TUOI,KH.TENKH FROM SINHVIEN
JOIN KHOA KH ON SINHVIEN.MaKH =KH.MaKH
WHERE DATEDIFF(YEAR, NgaySinh, GETDATE()) BETWEEN 20 AND 30;
go
select * from vw_cau12
go
-------cau 13 ------
select MASV,PHAI,MAKH,CASE WHEN HOCBONG>500000 THEN N'CAO' ELSE N'THAP' END AS MUCHOCBONG  
from sinhvien
SELECT MASV,PHAI,MAKH,IIF(HOCBONG>500000,N'CAO',N'THAP') AS MUCBOCBONG
FROM SINHVIEN
GO
CREATE VIEW vw_cau13 
as 
SELECT MASV,PHAI,MAKH,IIF(HOCBONG>500000,N'CAO',N'THAP') AS MUCBOCBONG
FROM SINHVIEN
go 



