----in ra du lieu cac bang 
select * from [dbo].[Ketqua]
SELECT *  FROM [dbo].[Khoa]
SELECT * FROM [dbo].[MonHoc]
SELECT * FROM [dbo].[SinhVien]
---- cau 1
select * FROM MONHOC
--- LIET KE DANH SACH SINH VIEN CAU2  MA SINH VIEN TANG DAN 
GO 
SELECT MASV,HOSV,TENSV,HOCBONG FROM SinhVien
ORDER BY MASV ASC
-----CAU 3 ---DANH SACH DUOC SAP XEP THEO THU TU CUA TEN
GO
SELECT MASV,TENSV,PHAI,DAY(NGAYSINH) DAY FROM SinhVien
ORDER BY TENSV ASC 
------CAU4 NGAY SINH TANG DAN VA HOC BONG GIAM DAN
GO
SELECT HOSV+' '+TENSV HOTEN ,DAY(NGAYSINH) DAY,HOCBONG FROM SinhVien
ORDER BY DAY(NGAYSINH) ASC,
HOCBONG DESC 
----CAU5 DS MON HOC BAT DAU BANG CHU T CAU5 []%
GO
SELECT * FROM MONHOC 
WHERE TENMH LIKE N'[T]%'
-----LAY TAT CA SINH VIEN CO CHU CAI CUOI CUNG TRONG TEN LA I
GO 
SELECT HOSV+' '+TENSV HOTEN,PHAI,DAY(NGAYSINH) DAY 
FROM SINHVIEN
WHERE TenSV LIKE N'%[I]'
-----LAY DANH SACH KHOA CO KY TU THU2 LA 'N',% LA CAC KY TU DANG SAU
GO
SELECT MAKH,TENKH FROM Khoa
WHERE TenKH LIKE N'_N%'
GO
----LIET KE NHUNG SINH VIEN CO MA HO CO CHUA CHU THI CAU 8
SELECT * FROM SinhVien
WHERE LOWER(HOSV) LIKE N'%THỊ%'
GO
------CAU 9 KYTU DAU TIEN CUA TEN NAM TRONG KHOANG TU A DEN M TANG DAN THEO TEN SV 
SELECT MASV,HOSV+' '+TENSV HOTEN ,PHAI,HOCBONG
FROM SinhVien
---WHERE TENSV >= 'A 'AND TENSV <='M'
WHERE TENSV BETWEEN 'A' AND 'M'
ORDER BY TENSV ASC
----DS SACH SINH VIEN KHOA ANH VAN
GO
SELECT MASV,HOSV+' '+TENSV HOTEN,DAY(NGAYSINH) DAY,MAKH
FROM SinhVien
WHERE MAKH=N'AV'
----WHERE MAKH LIKE N'AV%'
GO
----DS SINH VIEN KHOA VAT LY SAP XEP THEO THU TU NGAY SINH GIAM DAN CAU12
SELECT MASV,HOSV+' '+TENSV HOTEN,DAY(NGAYSINH) DAY,MAKH
FROM SinhVien
WHERE MAKH LIKE N'VL%'
ORDER BY DAY(NGAYSINH) DESC
---DS SINH VIEN CO HK BONG LONNHON 500000 VA SAP XEP THEO THU TU MA KHOA GIAM DAN CAU 13 
GO
SELECT MASV,HOSV+' '+TENSV HOTEN,DAY(NGAYSINH) DAY,MAKH,HOCBONG
FROM SinhVien
WHERE HocBong >500000
ORDER BY MAKH DESC 
GO
---- LIET KE SINH VIEN CO NGAY SINH 20/12/1987 CAU 14 
SELECT MASV,HOSV+' '+TENSV HOTEN,HOCBONG,NgaySinh
FROM SinhVien
---WHERE NgaySinh >CONVERT(DATETIME,('19871220'))
WHERE NGAYSINH ='1987-12-20'

GO 
---CAC SINH VIEN SINH SAU NGAY 20-12-1987,SAP XEP THEO THU TU NGAY SINH GIAM DAN
SELECT MASV,HOSV+' '+TENSV HOTEN,HOCBONG,NgaySinh,NOISINH,DAY(NGAYSINH) DAY
FROM SinhVien
---WHERE NgaySinh >'1987-12-20'
WHERE NgaySinh >(CONVERT (DATETIME,'19871220'))
ORDER BY DAY(NGAYSINH) DESC
GO
-----LIET KE SINH VIEN CO HOC BONG LON HON 10000 VA SINH SONG O THANH PHO HCM
SELECT MASV,HOSV+' '+TENSV HOTEN,HOCBONG,NgaySinh,NoiSinh
FROM SinhVien
WHERE HocBong >10000 AND  NOISINH LIKE N'%Tp. HCM%'
GO
-----DS SINH VIEN KHOA ANH VAN VA KHOA TRIET 
SELECT MASV,MAKH,PHAI 
FROM SinhVien
WHERE MAKH IN ('AV','TR')
---WHERE MAKH = 'AV' OR MAKH='TR'

