------TAO VIEW 
----CAU 1
SELECT * FROM SinhVien
SELECT HOSV+' '+TENSV AS HOTEN ,MAKH,NOISINH,HOCBONG FROM SinhVien WHERE HOCBONG >10000 AND NOISINH =N'Tp. HCM'
GO
CREATE VIEW vw_HocBong
AS
SELECT HOSV + ' ' + TENSV AS HOTEN, MAKH, NOISINH, HOCBONG
FROM SinhVien
WHERE HOCBONG > 100000 AND NOISINH = N'Tp. HCM'
GO
SELECT * FROM vw_HocBong
GO 
DROP VIEW vw_HocBong
-----DS SINH VIEN KHOA ANH VAN VA KHOA TRIET 
SELECT * FROM SINHVIEN WHERE MAKH IN ('AV','TR')
GO
CREATE VIEW vw_Khoa
as 
SELECT MASV,MAKH,PHAI FROM SinhVien WHERE MAKH IN ('AV','TR')
GO
SELECT * FROM vw_Khoa
GO 
-----CHO BT NHUNG SINH VIEN sinh ngay 1/1/1986 den 5/6/1992
SELECT * FROM SINHVIEN
WHERE NgaySinh BETWEEN '1986-01-01' AND '1992-06-05'
GO
CREATE VIEW vw_NGAYSINH
as 
SELECT MASV,NgaySinh,NoiSinh,HocBong FROM SINHVIEN
WHERE NgaySinh BETWEEN '1986-01-01' AND '1992-06-05'
GO
-----HOCBONG
CREATE VIEW vw_HOCBONG
as 
SELECT MASV,NgaySinh,PHAI,MAKH FROM SINHVIEN
WHERE HOCBONG BETWEEN 20000 AND 80000
GO
------SOTIET 
SELECT * FROM MonHoc
GO
CREATE VIEW vw_monhoc
as 
select MAMH,TENMH,SOTIET FROM MonHoc WHERE SOTIET BETWEEN 40 AND 60
GO
SELECT * FROM vw_monhoc
--------